### ISSUE TITLE
ResourceTimeLineView - onSelect() Method is broken

### ISSUE THREAD

**Issue by r4inX** [Servoy/fullcalendarcomponent2#10]
Hey Guys,

we got a problem. I updated my Servoy Project to **2023.12.2.3924**. Newest fullcalendar2 version **v2023.6.0**

Now i have the following problem/bug, which didnt happen in previous servoy versions.

I have a ResourceTimeLineView with mutliple resources. And i have a simple onSelect() Method which just application.output() the arguments of the method.

When i do a select over say 3 days in a resource, i get the following error in the console and the calendar gets blocked, the selected 3 days just stay selected and i cant select any other days.

`ERROR org.sablo.BrowserConsole - sendMessageObject@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:29539:22
callService@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:29531:12
callService@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:28488:36
executeEvent@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:17827:41
func@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:22001:31
49762/FullCalendar/this.selectCallback@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:170916:14
trigger@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:124483:15
triggerDateSelect@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:124535:19
23924/DateSelecting/this.handlePointerUp@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:131984:75
trigger@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:124483:15
23924/HitDragging/this.handlePointerUp@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:131722:20
trigger@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:124483:15
23924/FeaturefulElementDragging/this.onPointerUp@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:131537:22
trigger@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:124483:15
23924/PointerDragging/this.handleMouseUp@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:130820:20
invokeTask@http://localhost:8189/polyfills.js:529:171
onInvokeTask@http://localhost:8189/vendor.js:29846:22
invokeTask@http://localhost:8189/polyfills.js:529:54
onInvokeTask@http://localhost:8189/vendor.js:30158:25
invokeTask@http://localhost:8189/polyfills.js:529:54
runTask@http://localhost:8189/polyfills.js:333:37
invokeTask@http://localhost:8189/polyfills.js:606:26
invokeTask@http://localhost:8189/polyfills.js:1730:12
globalCallback@http://localhost:8189/polyfills.js:1771:33
globalZoneAwareCallback@http://localhost:8189/polyfills.js:1791:12
EventListener.handleEvent*customScheduleGlobal@http://localhost:8189/polyfills.js:1879:37
scheduleTask@http://localhost:8189/polyfills.js:519:16
onScheduleTask@http://localhost:8189/vendor.js:29839:21
scheduleTask@http://localhost:8189/polyfills.js:514:43
onScheduleTask@http://localhost:8189/polyfills.js:431:61
scheduleTask@http://localhost:8189/polyfills.js:514:43
scheduleTask@http://localhost:8189/polyfills.js:372:35
scheduleEventTask@http://localhost:8189/polyfills.js:397:19
15155/patchEventTarget/patchEventTargetMethods/makeAddListener/<@http://localhost:8189/polyfills.js:2030:27
23924/PointerDragging/this.handleMouseDown@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:130809:18
invokeTask@http://localhost:8189/polyfills.js:529:171
onInvokeTask@http://localhost:8189/vendor.js:29846:22
invokeTask@http://localhost:8189/polyfills.js:529:54
onInvokeTask@http://localhost:8189/vendor.js:30158:25
invokeTask@http://localhost:8189/polyfills.js:529:54
runTask@http://localhost:8189/polyfills.js:333:37
invokeTask@http://localhost:8189/polyfills.js:606:26
invokeTask@http://localhost:8189/polyfills.js:1730:12
globalCallback@http://localhost:8189/polyfills.js:1771:33
globalZoneAwareCallback@http://localhost:8189/polyfills.js:1791:12
EventListener.handleEvent*customScheduleGlobal@http://localhost:8189/polyfills.js:1879:37
scheduleTask@http://localhost:8189/polyfills.js:519:16
onScheduleTask@http://localhost:8189/vendor.js:29839:21
scheduleTask@http://localhost:8189/polyfills.js:514:43
onScheduleTask@http://localhost:8189/polyfills.js:431:61
scheduleTask@http://localhost:8189/polyfills.js:514:43
scheduleTask@http://localhost:8189/polyfills.js:372:35
scheduleEventTask@http://localhost:8189/polyfills.js:397:19
15155/patchEventTarget/patchEventTargetMethods/makeAddListener/<@http://localhost:8189/polyfills.js:2030:27
PointerDragging@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:130884:17
FeaturefulElementDragging@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:131549:34
DateClicking@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:131906:21
54089/CalendarContent/this.registerInteractiveComponent/interactions<@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:120064:72
54089/CalendarContent/this.registerInteractiveComponent@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:120064:45
2405/ResourceTimelineGrid/this.handleEl@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:134868:22
S@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57724:30
H@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57614:42
M@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57678:245
H@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57611:6
O@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57717:72
M@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57679:84
H@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57611:6
M@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57678:245
H@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57611:6
O@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57717:72
M@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57679:84
H@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57611:6
M@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57678:245
H@http://localhost:8189/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:57611:6
`

Can u please look at this as soon as possible? If not i need to rollback my servoy version to 23.9. We need that function asap back to functional.

I´ll try stuff out and keep u updated in this issue.

Greeting
-Rain

**Comment by jcompagner** [comment]
why would you downgrade servoy first?
if you want to test something downgrade first just the fullcalendar to a version that you previously used

**Comment by jcompagner** [comment]
but please attach a sample what you do so we can have a look

**Comment by r4inX** [comment]
> why would you downgrade servoy first? if you want to test something downgrade first just the fullcalendar to a version that you previously used

well, because with servoy 2023.09 we used the same fullcalender2 version 2023.6.0. the only thing i upgraded was servoy to 23.12.2 and now it wont work nomore.

i´ll get a sample ready for u to test.

**Comment by r4inX** [comment]
Hey, i created a sample solution. Needed to .zip it for github.
[fullcalendarTest.zip](https://github.com/Servoy/fullcalendarcomponent2/files/14373001/fullcalendarTest.zip)

I tested it on another computer, there i get the following error:

`ERROR org.sablo.BrowserConsole - TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLElement'
    |     property '__k' -> object with constructor 'Object'
    |     property 'props' -> object with constructor 'Object'
    |     ...
    |     property 'element' -> object with constructor 'ElementRef'
    --- property 'nativeElement' closes the circle
    at JSON.stringify (<anonymous>)
    at WebsocketSession.sendMessageObject (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:28660:22)
    at WebsocketSession.callService (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:28652:12)
    at SabloService.callService (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:27609:36)
    at FormService.executeEvent (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:17376:41)
    at FullCalendar.func [as onSelectMethodID] (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:21164:31)
    at FullCalendar.selectCallback (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:158938:14)
    at Emitter.trigger (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:118398:15)
    at triggerDateSelect (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:118450:19)
    at DateSelecting.handlePointerUp (http://localhost:8183/default-src_ngclient_allcomponents_module_ts-src_ngclient_allservices_service_ts-src_servoyco-f6c863.js:125906:75)`

**Comment by mvid-servoy** [comment]
The problem was found and fixed in the fullcalendar2 component (fix available with the next component release)

**Comment by r4inX** [comment]
@mvid-servoy hey, thanks for resolving the bug. 
Do you have a rough ETA on when the next comp-release is gonna be? I tried to pull the source and get it to work with that, but unfortunately without success. So i need to wait for the official-release. I have a critical meeting in 2 weeks, where this feature needs to be shown.
