### ISSUE TITLE
use momentplugin in the calendar

### ISSUE THREAD

**Issue by saleman67** [Servoy/fullcalendarcomponent2#11]
We would like to use the momentTimezonePlugin in the scheduler so we can show nice day names.
https://fullcalendar.io/docs/moment-timezone-plugin

**Comment by jcompagner** [comment]
we will not introduce moment anymore in our TiNG code base

moment is deprecated and not maintained anymore: https://momentjs.com/docs/#/-project-status/

**Comment by jcompagner** [comment]
we use the https://github.com/Servoy/fullcalendarcomponent2/blob/master/fullcalendarcomponent2/package.json#L30 luxon plugin for that so that should be usable
