### ISSUE TITLE
servoy 23.3.0 and fullcalendar2 23.3.0 | premium plugins dont work nomore

### ISSUE THREAD

**Issue by r4inX** [Servoy/fullcalendarcomponent2#2]
Updated my Servoy and all my compoments to 23.3.0. **Changed nothing in the code or otherwise**
My Calender with the premium plugin "resourceTimelineMonth" is not working anymore.
In servoy-console i get nothing, but in the firefox developer console i get the following:
see images.

Please let me know if there is a big api change or issue...

![fc2_1](https://user-images.githubusercontent.com/28804733/231488815-54b859b9-6468-48fd-a228-5cb685287a62.png)
![fc2_2](https://user-images.githubusercontent.com/28804733/231488822-62595ff1-4e19-474e-88c8-d4172efb8294.png)

**Comment by jcompagner** [comment]
i think the problem is those warnings about unknown options..
we did upgrade fullcalendar from 5 to 6 so it could be that they changed some stuff how to set stuff.

**Comment by r4inX** [comment]
hey @jcompagner i looked into the fullcalender docu, the only difference i´ve found is the following @import statements / npm installs (which we in servoy cant access)

**version 5:** 
`npm install --save @fullcalendar/core @fullcalendar/resource-timeline`
[https://fullcalendar.io/docs/v5/timeline-view](url)

**version 6:**
`npm install --save  @fullcalendar/core @fullcalendar/resource @fullcalendar/resource-timeline`
[https://fullcalendar.io/docs/timeline-view](url)


maybe there is something missing in the fullcalendar2 2023.3 webcomponent? 
thanks in advance

**Comment by r4inX** [comment]
solved with latest updates
